-- ============================================================
-- SECURITY FIX — Era of Robotics · Supabase mdzckxvxekeyxmvpjtka
-- Run this in: Supabase Dashboard → SQL Editor → New query
-- ============================================================

-- ── 1. LEADS TABLE ──────────────────────────────────────────
-- Ensure RLS is on (idempotent)
alter table if exists public.leads enable row level security;

-- Revoke all access from anon and authenticated roles explicitly
revoke all on public.leads from anon;
revoke all on public.leads from authenticated;

-- Drop old policy if it exists, recreate cleanly
drop policy if exists "Service role can manage leads" on public.leads;

create policy "Service role can manage leads"
  on public.leads
  as restrictive
  for all
  to service_role
  using (true)
  with check (true);


-- ── 2. ANALYTICS_EVENTS TABLE ───────────────────────────────
-- Create the table if it doesn't exist yet (safe to run if it does)
create table if not exists public.analytics_events (
  id          bigint generated by default as identity primary key,
  path        text,
  title       text,
  referrer    text,
  event_type  text not null default 'page_view',
  session_id  text,
  ip_address  text,
  user_agent  text,
  created_at  timestamptz not null default timezone('utc', now())
);

-- Enable RLS
alter table public.analytics_events enable row level security;

-- Revoke public access
revoke all on public.analytics_events from anon;
revoke all on public.analytics_events from authenticated;

-- Only service role can read/write
drop policy if exists "Service role can manage analytics" on public.analytics_events;

create policy "Service role can manage analytics"
  on public.analytics_events
  as restrictive
  for all
  to service_role
  using (true)
  with check (true);


-- ── 3. INDEX for analytics queries ──────────────────────────
create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

create index if not exists analytics_events_event_type_idx
  on public.analytics_events (event_type);


-- ── Verify ──────────────────────────────────────────────────
select
  schemaname,
  tablename,
  rowsecurity as rls_enabled
from pg_tables
where schemaname = 'public'
  and tablename in ('leads', 'analytics_events');
