create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  email text not null,
  source text,
  persona text,
  interest text,
  stage text,
  created_at timestamptz not null default timezone('utc', now()),
  ip_address text,
  user_agent text
);

create unique index if not exists leads_email_key on public.leads (lower(email));

alter table public.leads enable row level security;

-- Server-side writes should use the service role key and bypass RLS.
-- Public/browser clients should not insert directly into this table.

create policy "Service role can manage leads"
on public.leads
as permissive
for all
to service_role
using (true)
with check (true);
